name: cicd

on: pull_request

jobs:
    job-name:
        runs-on: ubuntu-latest
        steps:
        - run: pwd
        - run: ls -al
        - uses: actions/checkout@v4
        - run: ls -al
        - run: python --version
        - run: python -c "print('hello')"
