name: cicd-dev

on: 
    workflow_dispatch:
    push:
        branches: 
        - 'feat-**'
    pull_request:
        branches:
        - 'master'
        types: [closed]

jobs:
    deploy-dev:
        runs-on: ubuntu-latest
        steps:
        - run: echo deploy in dev