name: Deploy from Feature to Release

on:
  push:
    branches:
      - release/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: |
      startsWith(github.event.head_commit.message, 'Merge pull request') &&
      contains(github.event.head_commit.message, 'feature/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run your job
        run: echo "Deploying code from feature branch to release!"
