name: gitoutput

on:
  push:
    branches:
      - master

jobs:
  myjob:
    runs-on: ubuntu-latest

    steps:
      - name: mystep
        id: mystep
        run: echo "message=hello" >> $GITHUB_OUTPUT

      - name: read
        run: echo "Output from mystep ${{ steps.mystep.outputs.message }}"
